### ISSUE TITLE
Clarify to users to log in with SciServer control rather than CasJobs control

### ISSUE THREAD

**Issue by raddick** [idies/CasJobs#10]
On the CasJobs login page:

http://scitest02.pha.jhu.edu/CasJobs/login.aspx

Make sure users understand that they should log in by clicking "Login" on the SciServer control on the top right rather than the old-fashioned CasJobs User ID / Password box.

Part of the solution is probably to remove the old control and leave only the new control.

**Comment by mikear69** [comment]
This is related to #31 and #33.  Please see proposed solution posted there.

**Comment by mtaghiza** [comment]
Closing because it is already being discussed elsewhere.
