### ISSUE TITLE
Password reset/recovery feature

### ISSUE THREAD

**Issue by raddick** [idies/CasJobs#14]
Right now, if a user forgets their password, their only option is to email the helpdesk. That's an additional step for the user, and I suspect some users are just giving up at that point.

Let's create a password reset or recovery feature for CasJobs, like many other sites have.

**Comment by raddick** [comment]
I think this is actually associated with the portal rather than with CasJobs per se. I'll probably move it there soon. In which case I'll then close this issue.

**Comment by mikear69** [comment]
This is now fixed with the new Login Portal.  Will be closed.

**Comment by mtaghiza** [comment]
Closing...
