### ISSUE TITLE
Submit Queries: which output table name has priority?

### ISSUE THREAD

**Issue by raddick** [idies/CasJobs#16]
On the Submit Query page:

http://scitest02.pha.jhu.edu/CasJobs/SubmitJob.aspx

When a user a table name in the "Table (optional)" box at the top, and types a different table name in the "into" clause of the query:

select top 10000000 * into mydb.scidrive_test1_v3 from dr10.photoobj

...which table name takes priority when the user clicks Submit? What should they expect the table to be called in their MyDB?

I'm not sure what the desired behavior is, but we should at least discuss, and make it clear in the user guide.

**Comment by raddick** [comment]
You can probably figure this out just by experimenting.

**Comment by thakar** [comment]
Note that this is not a new problem, i.e. it exists in the live CasJobs.

As such, I believe it should be labeled v_next unless it prevents a user
from doing something.

      Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Belief in the supernatural reflects a failure of the imagination.
[Edward Abbey, naturalist and author (1927-1989)]

**Comment by raddick** [comment]
This is just a question, so it's not associated with any version. It's a discussion item.

Experiment shows that the answer is that anything you type in an "into" clause in the query window gets the priority.

Is this the behavior we want?

If we decide the behavior needs to change, I'll label this as v_next, but for now, let's just talk about it here under a "question" label.

**Comment by thakar** [comment]
I think that is fine as is, i.e. what is in the query window (INTO clause)
should take precedence.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
You may have a fresh start any moment you choose, for this thing
we call failure is not the falling down, but the staying down.
[Mary Pickford]

**Comment by raddick** [comment]
OK, that's the desired behavior. It'll need to be documented, but that will be a separate issue, labeled as Documentation. Closing this issue.
