### ISSUE TITLE
Large query fails (was attempting to test SciDrive integration)

### ISSUE THREAD

**Issue by raddick** [idies/CasJobs#17]
Attempting to test the last step in CJ_SCIDRV_1 by running a huge query. I attempted to submit the following query:

select top 10000000 * into mydb.scidrive_test1_v3 from dr10.photoobj

and I got a status of "Failed" with the following error message:

"Could not allocate space for object 'mydb.scidrive_test1_v3' in database 'MYDB_1727558787' because the 'PRIMARY' filegroup is full. Create disk space by deleting unneeded files, dropping objects in the filegroup, adding additional files to the filegroup, or setting autogrowth on for existing files in the filegroup."

I think this is the proper error message to display in this case, but should this query succeed? Ten million rows from dr10.photoobj is a lot, but shouldn't be too excessive to run in Casjobs, right?

**Comment by raddick** [comment]
Update: fails with the same error message for selecting 10,000 rows, which definitely should work.

Note that this is not related to SciDrive integration, because this is happening at the Submit Query stage.

**Comment by thakar** [comment]
No, this is also way too big for the default MyDB size.  Each row of
PhotoObj is ~ 2kb in size.

This is not a bug, rather you are exceeding your MyDB size.

   Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Do not commit the error, common among the young, of assuming that
if you cannot save the whole of mankind, you have failed.
[Jan de Hartog]

**Comment by thakar** [comment]
Sorry I lied, 10k rows is not too big for an empty MyDB, but the previous
failed query must have filled it up.

   Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Do not commit the error, common among the young, of assuming that
if you cannot save the whole of mankind, you have failed.
[Jan de Hartog]

**Comment by raddick** [comment]
OK, that was it. Thanks!

This is still a documentation issue, because we'll need to give the user a clearer error message that says that the query failed because it filled up the user's MyDB. I'll file that as a separate ticket as a v_next enhancement.

I'm holding off on further testing for the moment, but I will eventually need to re-run this test with a larger table.

Mitya, could you please raise my MyDB space so I can test SciDrive integration with a larger query?

**Comment by raddick** [comment]
The bug part of this is fixed. This was a tester error.

**Comment by raddick** [comment]
...and Mitya promoted user "raddick" to an admin, so I can bump my own CasJobs MyDB size. Closing the "question" part too.
