### ISSUE TITLE
v1_0_0: Import of large file fails with 404 error page

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#36]
If you use the file import option on the Import page and choose a file that is larger than the max limit, the import page goes into loading state for 30+ seconds, then displays a 404 error page:

Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

The same thing works on the production casjobs (displays the correct errror that the file is too large).

**Comment by raddick** [comment]
This only applies to file uploads larger than the stated maximum file size limit, right?

This is a bug related to error handling; labeled with both labels.

**Comment by dmedv** [comment]
Fixed. Configuration problem.
Had to increase maxAllowedContentLength in Web.config to allow requests larger than 100G.
After that there is no 404 error, and CasJobs correctly displays it's own error message, that the file size exceeds the limit.
