### ISSUE TITLE
v1_0_0: Folder name case-sensitive in MyDB download to SciDrive (?), returning internal server error

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#38]
I created a folder "/Misc" in SciDrive, then tried to download from MyDB to SciDrive, changing the default folder to "/misc", and it twice gave me the same error:
The remote server returned an error: (500) Internal Server Error. at System.Net.HttpWebRequest.GetResponse() at edu.jhu.Cas.Service.OutputThread.ProcessJob(Job job) in e:\Projects\github\idies\CasJobs\JobsService\OutputThread.cs:line 133

If I change the folder name to /Misc on the MyDB download page, then it works fine.

**Comment by dmedv** [comment]
Added a user-friendly error message in case of upload failure: ‘There was a problem accessing the folder “/<folder name>”, please verify that it exists, and note that folder names are case sensitive’. Marking as closed.
