### ISSUE TITLE
v1_0_0: Sharing MyScratch tables does not work

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#40]
Tried sharing a MyScratch table with another user and viewing it in the second user's MyDB page or running a query on the MyScratch table on the second user's query page.  Neither worked.  On the MyDB page, although the table gets listed when the appropriate group is selected in the dropdown menu, clicking on it causes a red message to appear on the top of the right frame: "This table no longer exists and has been removed from publication."  If you run a query on the query page: SELECT TOP 10 * FROM [myscratch:default]:<user>.<table>, it also fails with the error message "Object reference not set to an instance of an object."

**Comment by dmedv** [comment]
Fixed. Marking as closed. Please note, that sharing MyScratch tables is an experimental feature, and is not supposed to be stable, user-friendly, etc..
