### ISSUE TITLE
Stop immediate redirect for not-logged-in users

### ISSUE THREAD

**Issue by raddick** [idies/CasJobs#9]
Right now, when a not-logged-in user goes to the CasJobs home page:

http://scitest02.pha.jhu.edu/CasJobs/

They get immediately redirected to the login portal page. This is extremely confusing for the user - by going to CasJobs, they suddenly find themselves on an unlabeled site that has nothing to do with CasJobs.

It's OK to have the login happen on a separate site (although we should consider this carefully), but we must start the user off on a page they recognize. Instead, there should be a prominent link in the top of the instructions on the home page asking users to click to log in on the portal site.

**Comment by raddick** [comment]
After discussion with Ani and Mitya: let's leave this as-is for this release. We can reconsider and maybe fix in v_next. Changed from a bug to a v_next enhancement.

**Comment by dmedv** [comment]
Showing home page by default. Removed login/logout items from CasJobs menu. Marking this as fixed.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_0_2
